### PR TITLE
towards standard ellipse overlay

### PR DESCRIPTION
**Pull request by dehann**

### CODE REVIEW

**Comment by andreasnoack** [comment]
# [Codecov](https://codecov.io/gh/JuliaRobotics/RoMEPlotting.jl/pull/77?src=pr&el=h1) Report
> Merging [#77](https://codecov.io/gh/JuliaRobotics/RoMEPlotting.jl/pull/77?src=pr&el=desc) into [master](https://codecov.io/gh/JuliaRobotics/RoMEPlotting.jl/commit/9555512d6e976044a3852a169c3295cfb49b2bdc&el=desc) will **increase** coverage by `0.51%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/JuliaRobotics/RoMEPlotting.jl/pull/77?src=pr&el=tree)

```diff
@@            Coverage Diff            @@
##           master     #77      +/-   ##
=========================================
+ Coverage    6.59%   7.10%   +0.51%     
=========================================
  Files           5       5              
  Lines        1047    1098      +51     
=========================================
+ Hits           69      78       +9     
- Misses        978    1020      +42     
```


| [Impacted Files](https://codecov.io/gh/JuliaRobotics/RoMEPlotting.jl/pull/77?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [src/SolverVisualization.jl](https://codecov.io/gh/JuliaRobotics/RoMEPlotting.jl/pull/77/diff?src=pr&el=tree#diff-c3JjL1NvbHZlclZpc3VhbGl6YXRpb24uamw=) | `1.70% <0.00%> (-0.02%)` | :arrow_down: |

------

[Continue to review full report at Codecov](https://codecov.io/gh/JuliaRobotics/RoMEPlotting.jl/pull/77?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/JuliaRobotics/RoMEPlotting.jl/pull/77?src=pr&el=footer). Last update [13d547b...1efc79f](https://codecov.io/gh/JuliaRobotics/RoMEPlotting.jl/pull/77?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by dehann** [comment]
also closes #73

**Comment by dehann** [comment]
HI @Affie , this might be useful for the parametric covariance work too.  This is a work in progress for standard option to draw fitted ellipse to variable belief estimates.

**Comment by Affie** [comment]
Thanks, I was planning to look at it after covariance calculation.

**Pull request merged**
